services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/orders_db
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    container_name: backend-db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: backend-adminer-1
    restart: always
    ports:
      - "8081:8080"

  redis:
    image: redis:7
    container_name: backend-redis-1
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
